import mongoose from "mongoose";
import { Schema } from "mongoose";

const parentsSchema = new Schema({
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    parentId: { type: String, required: true, unique: true },
    familyNumber: { type: String, required: true },
    lastName: { type: String },
    firstName: { type: String },
    middleName: { type: String },
    contact: { type: Number },
    phNumber: { type: String },
    clientType: { type: String },
    ifMember: { type: String },
    birthday: { type: Date },
    address: { type: String },
    dependents: { type: Number },
    civilStatus: { type: String },
    maidenName: { type: String },
    spouseName: { type: String },
    partnerName: { type: String },
    occupation: { type: String },
    educAttainment: { type: String },
    empStatus: { type: String },
    date: { type: Date },
    kpp: { type: String },
    sex: { type: String },
    religion: { type: String },
    age: { type: Number },
    pallergy: { type: String },
    pasthma: { type: String },
    pspecifyAllergy: { type: String},
    pcancer: { type: String },
    porganCancer: { type: String },
    pcerebrovascular: { type: String },
    pcoronaryArtery: { type: String },
    pdiabetes: { type: String },
    pemphysema: { type: String },
    pepilepsy: { type: String },
    phepatitis: { type: String },
    phyperlipidemia: { type: String },
    phypertension: { type: String },
    ppepticUlcer: { type: String },
    ppneumonia: { type: String },
    pthyroid: { type: String },
    ppulmonaryTb: { type: String },
    ppulmonaryTbCategory: { type: String },
    pextrapulmonaryTb: { type: String },
    pextrapulmonaryTbCategory: { type: String },
    puti: { type: String },
    pmentalIllness: { type: String },
    pothers: { type: String },
    pnone: { type: String },
    pbloodPressure: { type: String },
    fallergy: { type: String },
    fasthma: { type: String },
    fspecifyAllergy: { type: String },
    fcancer: { type: String },
    forganCancer: { type: String },
    fcerebrovascular: { type: String },
    fcoronaryArtery: { type: String },
    fdiabetes: { type: String },
    femphysema: { type: String },
    fepilepsy: { type: String },
    fhepatitis: { type: String },
    fhyperlipidemia: { type: String },
    fhypertension: { type: String },
    fpepticUlcer: { type: String },
    fpneumonia: { type: String },
    fthyroid: { type: String },
    fpulmonaryTb: { type: String },
    fpulmonaryTbCategory: { type: String },
    fextrapulmonaryTb: { type: String },
    fextrapulmonaryTbCategory: { type: String },
    futi: { type: String },
    fmentalIllness: { type: String },
    fothers: { type: String },
    fnone: { type: String },
    fbloodPressure: { type: String },
    smoking: { type: String },
    packsPerYear: { type: Number },
    alcohol: { type: String },
    bottlesPerDay: { type: Number },
    illicitDrugs: { type: String },
    illicitDrugsDetails: { type: String },
    sexualHistory: { type: String },
    sexualHistoryDetails: { type: String },
    menarche: { type: Number },
    pregnancyHistory: { type: String },
    menopause: { type: String },
    gravida: { type: Number },
    ageOfMenopause: { type: Number },
    para: { type: Number },
    lmp: { type: Date },
    fullTerm: { type: Number },
    preTerm: { type: Number },
    abortion: { type: Number },
    living: { type: Number },
    intervalOfMenstruation: { type: String },
    duration: { type: Number },
    padsPerDay: { type: Number },
    dateComplaints: { type: Date },
    chiefComplaints: { type: String },
    bp: { type: String },
    hr: { type: String },
    o2sat: { type: String },
    wt: { type: String },
    temp: { type: String },
    rr: { type: String },
    ht: { type: String },
    bmi: { type: String },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
});

const Parents = mongoose.model("Parents", parentsSchema);
export default Parents;